name: main workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
    - dev
  workflow_dispatch:

jobs:
  main:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: main step
        run: echo "Main Step"
        shell: bash
  dev:
    run-on: ubuntu-latest
    steps:
      - name: gm
        run: echo "GM Buenos!"
        shell: bash